### ISSUE TITLE
CSS Bundling, Rails 7 and Bootstrap

### ISSUE THREAD

**Issue by resistorsoftware** [rails/cssbundling-rails#102]
New Rails 7 App with ESBuild, and Bootstrap. It works. OK. Great. Builds fine.

In the provided app/assets/stylesheets/application.bootstrap.scss file, if I were to add a single class of valid code to use an image, it all breaks. For example: 

    .test {
       background-image: image-url("foo.jpg");
    }

For whatever reason, when the sass command tries to build that, the build blows up with errors. Specifically, the long-ass fingerprint signature added to the asset is part of the error. Not sure why. It seems the helpers for sass are not being digested properly as per the old sassc-rails gem. So what is the modern way to go here?   

What is the secret to using the needed helpers to get assets into Sass with the new setup and CSS Bundling gem?

**Comment by PedroAugustoRamalhoDuarte** [comment]
@resistorsoftware i thinks is the same problem with this issue: https://github.com/rails/cssbundling-rails/issues/22

**Comment by jasonfb** [comment]
@resistorsoftware did you try
```
.test {
   background-image: url("foo.jpg");
}
```
I think this got added to Sprockets here: https://github.com/rails/sprockets-rails/pull/476/files

**Comment by jasonfb** [comment]
https://github.com/rails/sprockets-rails#initializer-options
```
config.assets.resolve_assets_in_css_urls

When this option is enabled, sprockets-rails will register a CSS postprocessor to resolve assets referenced in [url()](https://developer.mozilla.org/en-US/docs/Web/CSS/url()) function calls and replace them with the digested paths. Defaults to true.
```
