### ISSUE TITLE
Should assets build be added to git repo?

### ISSUE THREAD

**Issue by rctneil** [rails/cssbundling-rails#103]
As per the title,  Should my Assets/build directories be added to my git repo?

I'm a bit confused by what should and should not be committed. and there does not appear to be any documentation or guidance to tell us what to do regarding this.

Neil

**Comment by jasonfb** [comment]
in a default new Rails app, the `.gitignore` file contains this:

```
/app/assets/builds/*
!/app/assets/builds/.keep
```

so, I'd recommend going with the grain here and following along with what Rails new does.
