### ISSUE TITLE
Error: The linux-x64 architecture is incompatible with this module, link skipped.

### ISSUE THREAD

**Issue by ElenaSukhorukova** [rails/cssbundling-rails#108]
Hi, everyone. 
I try to set bootstrep in my project via sccbuilding, but after `rails css:install:bootstrap` I get the next errors:
`➤ YN0000: ┌ Link step
➤ YN0076: │ @esbuild/android-arm@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ @esbuild/linux-loong64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-android-64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.    
➤ YN0076: │ esbuild-android-arm64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped. 
➤ YN0076: │ esbuild-darwin-64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.     
➤ YN0076: │ esbuild-darwin-arm64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.  
➤ YN0076: │ esbuild-freebsd-64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.    
➤ YN0076: │ esbuild-freebsd-arm64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped. 
➤ YN0076: │ esbuild-linux-32@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-arm@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-mips64le@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-ppc64le@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-riscv64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-linux-s390x@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-netbsd-64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-openbsd-64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-sunos-64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-32@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ esbuild-windows-arm64@npm:0.15.15 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ fsevents@patch:fsevents@npm%3A2.3.2#~builtin<compat/fsevents>::version=2.3.2&hash=18f3a7 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0076: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 The linux-x64 architecture is incompatible with this module, link skipped.
➤ YN0000: └ Completed in 0s 998ms
➤ YN0000: Done with warnings in 1s 901ms`

I use wsl-2 Ubuntu 20.04.5 LTS and Rails 7. My package.json:
`{
  "dependencies": {
    "@hotwired/stimulus": "^3.1.1",
    "@hotwired/turbo-rails": "^7.2.4",
    "@popperjs/core": "^2.11.6",
    "bootstrap": "^5.2.3",
    "bootstrap-icons": "^1.10.2",
    "esbuild": "^0.15.15",
    "popper": "^1.0.1",
    "sass": "^1.56.1"
  },
  "scripts": {
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules",
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets"
  }
}`

How to fix it and should it be fixed? 
I will be glad for help!

**Comment by jasonfb** [comment]
what version of node?
Try with a production version of node (even numbered), like 14, 16, or 18
