### ISSUE TITLE
Rails 5 + ruby 2.5 support

### ISSUE THREAD

**Issue by F-3r** [rails/cssbundling-rails#121]
We are upgrading a Rails 5 (Ruby 2.5) application and decided to jump ahead and use cssbundling-rails and jsbundling-rails to target Rails 7 asset tooling directly.
Making both gems support Rails 5 and Ruby 2.5 were tiny fixes in install scripts. 
Inspite of both Rails 5 and Ruby 2.5 being in EoL, I thought it might help other people upgrading their apps.
If you folks would you be interested in extending the support officially I can submit a PR for review.

Cheers!

**Comment by dhh** [comment]
I'd post your changes here, so others can find them searching. But don't want to support EOL versions that old.
