### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by jetienne** [rails/cssbundling-rails#127]
I updated my yarn packages a few days ago, and I got the following warning:

$ yarn build:css:compile && yarn build:css:prefix
10:27:41 css.1    | $ sass ./app/assets/stylesheets/application.bootstrap.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules
10:27:41 css.1    | DEPRECATION WARNING: Passing percentage units to the global abs() function is deprecated.
10:27:41 css.1    | In the future, this will emit a CSS abs() function to be resolved by the browser.
10:27:41 css.1    | To preserve current behavior: math.abs(100%)
10:27:41 css.1    | To emit a CSS abs() now: abs(#{100%})
10:27:41 css.1    | More info: https://sass-lang.com/d/abs-percent
10:27:41 css.1    | 
10:27:41 css.1    |    ╷
10:27:41 css.1    | 57 │   $dividend: abs($dividend);
10:27:41 css.1    |    │              ^^^^^^^^^^^^^^
10:27:41 css.1    |    ╵
10:27:41 css.1    |     node_modules/bootstrap/scss/vendor/_rfs.scss 57:14         divide()
10:27:41 css.1    |     node_modules/bootstrap/scss/mixins/_grid.scss 59:12        row-cols()
10:27:41 css.1    |     node_modules/bootstrap/scss/mixins/_grid.scss 85:13        @content
10:27:41 css.1    |     node_modules/bootstrap/scss/mixins/_breakpoints.scss 68:5  media-breakpoint-up()
10:27:41 css.1    |     node_modules/bootstrap/scss/mixins/_grid.scss 72:5         make-grid-columns()
10:27:41 css.1    |     node_modules/bootstrap/scss/_grid.scss 38:3                @import
10:27:41 css.1    |     bootstrap/scss/bootstrap.scss 20:9                         @import
10:27:41 css.1    |     app/assets/stylesheets/application.bootstrap.scss 1:9      root stylesheet
10:27:41 css.1    |

**Comment by rafaelfranca** [comment]
This deprecation is on the bootstrap code, not in this gem. Could you report to the bootstrap repository? Thanks
