### ISSUE TITLE
Dependency issues with postcss-preset-env

### ISSUE THREAD

**Issue by ryanb** [rails/cssbundling-rails#29]
The `postcss-preset-env` package hasn't released a new version in 2 years and is starting to cause dependency issues. For example, this warning shows up when using the latest version of `tailwindcss` since the autoprefixer versions conflict.

```
tailwindcss@2.2.15" has unmet peer dependency "autoprefixer@^10.0.2"
```

I recommend removing `postcss-present-env` from the default install and including the plugins directly. For example, add `autoprefixer` and `postcss-nesting` packages if that's what is used by the app.

This results in fewer npm dependencies and a faster postcss build because it is only doing what the app needs.

**Comment by dhh** [comment]
Happy to take a patch that just does autoprefixer and css nesting as a smaller default area 👍
