### ISSUE TITLE
how can i reference a image on my .scss file?

### ISSUE THREAD

**Issue by gleydsonst** [rails/cssbundling-rails#34]
Hello, I changed my rails application 6 to work with cssbundling instead webpacker. This is working perfectly on dev, but on prod, the link for images on style.scss is broken.
```
footer {
  background-image: url('ruby.png');
}
```
this works on dev, but in prod, I'm getting a 404 error. O noticed that the file is created in the /public/assets/ but for some reason the link returned is not the same. I mean without the hash in the name _ruby-123a82sc347274ds63746a1wdhj32-png_ just https://mysite.com/assets/ruby.png

**Comment by dhh** [comment]
Duplicate of https://github.com/rails/cssbundling-rails/issues/22.
