### ISSUE TITLE
cssbundling-rails with Tailwind JIT  not watching file changes

### ISSUE THREAD

**Issue by weilandia** [rails/cssbundling-rails#35]
In order for new Tailwind classes to build when using JIT mode, a manual rebuild is required making development with JIT difficult.

There is some troubleshooting tips for this on in the [Tailwind docs](https://tailwindcss.com/docs/just-in-time-mode#troubleshooting), but it's not clear how I can use their suggestions without having separate dev and build scripts.

```
   // package.json
  // ...
    "build:tailwind": "tailwindcss -i ./app/assets/stylesheets/v2.tailwind.css -o ./app/assets/builds/v2.css",
    "build:sass": "sass ./app/assets/stylesheets/v1.sass.scss ./app/assets/builds/v1.css --load-path=node_modules --embed-sources",
    "build:css": "yarn run build:tailwind & yarn run build:sass"
```

cssbundling-rails (0.1.7)
rails (6.1.3.2)

**Comment by weilandia** [comment]
Changing the Procfile.dev from

```
web: bundle exec rails s --port 3000
css: yarn build:css --watch
js: yarn build --watch
```

TO

```
web: bundle exec rails s --port 3000
tailwind: TAILWIND_MODE=watch yarn build:tailwind --watch
sass: yarn build:sass --watch
js: yarn build --watch
```
fixes the issue.

**Comment by MrHubble** [comment]
@weilandia what does your build script in `package.json` look like? For example:

```js
"scripts": {
  "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css"
},
```
