### ISSUE TITLE
How to import relative css files?

### ISSUE THREAD

**Issue by thomasvanholder** [rails/cssbundling-rails#39]
The __bundle:css__ command bundles the `app/assets/stylesheets/application.tailwind.css` file. How to include relative css files to be bundled too?

File structure
```
|-- stylesheets
  |-- application.tailwind.css  
  |-- custom.css   
```

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@import "custom";  /* does not include the relative file.*/
```

**Comment by dhh** [comment]
Documented the this question as part of the FAQ: https://github.com/rails/cssbundling-rails/commit/2a17da2f254a96fa82eed6b57a4932905f17c2bb.

**Comment by RomanKrasavtsev** [comment]
It should also be mentioned here that in order to use `<%= stylesheet_link_tag "application", "custom" %>` we have to specify `//= link_tree ../stylesheets` in `app/assets/config/manifest.js`. Correct me if I am wrong.

**Comment by dhh** [comment]
That's right. But also the default setup. So you'd have to have actively removed it not to see that. Or have you found another way it's missing?

**Comment by simon-bigsofa** [comment]
Had to add `//= link_tree ../stylesheets` to `app/assets/config/manifest.js` manually after a fresh install.

This line is being removed from the default setup here during install:
https://github.com/rails/cssbundling-rails/blob/d920bc33de848a4bb31746ffb62e020d2ba6bce2/lib/install/install.rb#L9

**Comment by dhh** [comment]
Hmm, yeah, there's that conflict again where we're using the same directory for both styles that need compiling and those that do not. Need to figure a better solution for this.

**Comment by jmarsh24** [comment]
This is still an issue on new builds
