### ISSUE TITLE
Fix Rake CSS Build task error with Yarn binary not being found

### ISSUE THREAD

**Issue by bkuhlmann** [rails/cssbundling-rails#43]
## Overview

I'm afraid the [0.2.5 patch](https://github.com/rails/cssbundling-rails/commit/15d84715e41a95cfc3582d68dc6b4c0a336c84ed) introduced a bug with asset compilation both for local development and when deploying to Heroku in which the `yarn` binary can no longer be found.

## Steps to Recreate

To recreate, run `rails css:build` locally and you'll now see the following output in your console:

``` 
/Users/bkuhlmann/.cache/frum/versions/3.0.2/bin/ruby: No such file or directory -- /Users/bkuhlmann/Engineering/Companies/demo/bin/yarn (LoadError)
/Users/bkuhlmann/.cache/frum/versions/3.0.2/bin/ruby: No such file or directory -- /Users/bkuhlmann/Engineering/Companies/demo/bin/yarn (LoadError)
yarn run v1.22.17
$ sass ./app/assets/stylesheets/application.sass.scss ./app/assets/stylesheets/application.css --no-source-map --load-path=node_modules
✨  Done in 0.56s.
```

While the above isn't a catastrophic failure locally, it does crash Heroku deployments (might affect other server too). Here's an example where you can see the above failure but via my CLI when talking to a Heroku Stage server:

![iTerm2-84zdHHjW](https://user-images.githubusercontent.com/50245/142062080-b506d166-5018-460e-92c5-1206f5922ce6.png)

## Desired Behavior

I don't know if a revert of the above patch is necessary but maybe we need to split compilation between a development and production environment for deployment purposes? Either that or fix the root problem where Rake can't detect the `yarn` binary?

## Environment

- **Ruby**: ruby 3.0.2p107
- **Rails**: 6.1.4.1
- **CSS Bundling Rails**: 0.2.5
- Heroku

**Comment by liangmicha** [comment]
Here's a workaround that we've been using to patch the issue within our own codebase:
```
# lib/tasks/css_build_workaround.rake
namespace :css do
  desc "Workaround for css:build"
  task :build_workaround do
    system("yarn install")
  end
end

Rake::Task["css:build"].enhance ["css:build_workaround"]
```

**Comment by dhh** [comment]
So this is fixed on rails/main via https://github.com/rails/rails/pull/43641. But yeah, need to come up with a solution where we're not running yarn install twice on Rails 6.1.4 but also dealing with the fact that bin/yarn might not be there. cc @zarqman

**Comment by dhh** [comment]
Reverted via https://github.com/rails/cssbundling-rails/commit/b1a456287d3df1560947c8bbb0858518ae51dad8 for now.

I think the correct solution for double yarn install is to zero out yarn:install for Rails 6.1.x (it's already not used with rails/main).
