### ISSUE TITLE
Tailwind bundling does not work with HAML views

### ISSUE THREAD

**Issue by stebo** [rails/cssbundling-rails#46]
If I understand correctly, cssbundling-rails watches my css files as well as my view files and re-builds the `application.css`, to only included css properties that have been used in the templates.

This works well for `html.erb` views, **but not with** `html.haml`.

#### With HTML 

Create any view file, e.g. `new.html.erb` and copy paste the HTML from the Tailwind example here [https://play.tailwindcss.com/](https://play.tailwindcss.com/)

Re-build `application.css` using `yarn build:css` 

Open the view in a browser and it will look like its supposed to be:
<img width="752" alt="tailwind1" src="https://user-images.githubusercontent.com/5079061/144724766-78320e6c-5b37-4459-bcdb-a118ed41a4eb.png">

#### With HAML 
  
Now, install the `haml` Gem, rename your view to `new.html.haml` and use some html2haml converter to switch from HTML to HAML. 

Re-build `application.css` using `yarn build:css` 

If you open the view in a browser again, it will not look correctly as the corresponding css classes are missing in `application.css`:
<img width="798" alt="tailwind2" src="https://user-images.githubusercontent.com/5079061/144724810-1fd90c80-c758-46cf-bb2f-614f7362df11.png">

### Conclusion & Findings

When using HAML views, the required css properties will not at all or not partially be bundled into `application.css`.

This can also be shown when comparing file sizes in the above stated scenarios: when using `html.erb` the bundled `application.css` will always have a couple KB more than when re-building with `html.haml`.

Also: when re-naming a `xxx.html.erb` file, `yarn build:css --watch` will automatically re-build your css. This does not happen if you use HAML files.

### Fixes

Can anyone point me in the right direction on how to fix this in general or how to make HAML views also be working for my project? Any help appreciated!

**Comment by t27duck** [comment]
The default tailwind configuration provided by the gem assumes erb files for its purge option. Since it's not looking for any haml files, they are skipped and the classes are purged from the built css.

See: https://github.com/rails/cssbundling-rails/blob/main/lib/install/tailwind/tailwind.config.js#L3

You should have the equivalent file in the root of your application. Does changing the file extension in the `purge` list from "erb" to "haml" fix your problem?

**Comment by dhh** [comment]
What t27duck said 👍
