### ISSUE TITLE
7.0 upgrade issues with `assets:clobber` task

### ISSUE THREAD

**Issue by holman** [rails/cssbundling-rails#51]
```
› rails --trace
rails aborted!
Don't know how to build task 'assets:clobber' (See the list of available tasks with `rails --tasks`)
Did you mean?  assets:clean
/Users/holman/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task_manager.rb:59:in `[]'
/Users/holman/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:405:in `[]'
/Users/holman/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/cssbundling-rails-1.0.0/lib/tasks/cssbundling/clobber.rake:8:in `<main>'
[snip]
```

This app was on 6.0 using `tailwindcss-rails`. Upgraded to 7.0 with `rails app:update` and started to re-install tailwind via the new `cssbundling-rails` approach but ran into this error.

Probably something simple I'm missing with my existing tailwind setup — I can't reproduce this on a fresh Rails app — but thought I'd mention it in case there's an issue with upgrading.

**Comment by rmacklin** [comment]
Could it be related to [this change](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#sprockets-is-now-an-optional-dependency)? `sprockets-rails` is no longer a dependency of `rails`, so if your app doesn't have an explicit `sprockets-rails` dependency the gem may have been removed when you upgraded to rails 7.0 (easiest way to check that would be looking at your `Gemfile.lock`'s diff).

**Comment by holman** [comment]
Yup, that would indeed be it! (guides.rubyonrails.org hasn't been bumped to 7.0.0 yet and I didn't think to peek at the edge upgrade guides yet, either.)

Definitely a bit confusing on which underlying assets-related libraries are still being used or not being used or which is going to be changing post 7.0 and which aren't, hah. Still catching up with it yet. :) Thanks!

**Comment by rmacklin** [comment]
You're welcome!

Yeah, I noticed guides.rubyonrails.org was still on 6.1 when I was replying above. It seems to have just been updated, though!

![image](https://user-images.githubusercontent.com/1863540/146301964-04365c65-e686-4283-96c6-6a781fbd12ce.png)
