### ISSUE TITLE
Bootstrap 5 form-select

### ISSUE THREAD

**Issue by hoffdog** [rails/cssbundling-rails#60]
**Issue:**
Form select element (form-select) are not rendering with Bootstrap 5 (BS) styling. 

Spun up a brand new Rails 7 test application with the latest gem releases, pasted in some boiler plate BS styling and the select element are not being styled. It appears other styling properties of BS are working as expected.  Tried this with two separate applications, both running Rails 7.

<img width="930" alt="Screen Shot 2021-12-27 at 4 14 25 PM" src="https://user-images.githubusercontent.com/26173648/147513110-3177830b-2435-4da5-983c-917152f607cb.png">

Boiler Plate BS5 Code
```
<div class="col-md-4">
    <label for="inputState" class="form-label">State</label>
    <select id="inputState" class="form-select">
      <option selected>Choose...</option>
      <option>Test</option>
    </select>
</div>
```

**Comment by MrHubble** [comment]
Do you have a sample repo?

**Comment by MrHubble** [comment]
@hoffdog is this still a problem for you or can this issue now be closed?
