### ISSUE TITLE
Rails 7 and TailwindUI components with JavaScript are not working

### ISSUE THREAD

**Issue by skaeneman** [rails/cssbundling-rails#61]
**Steps to reproduce**
`rails new my_app -j esbuild --css tailwind --database=postgresql`
`cd my_app`
`bin/dev`

in my gemfile both jsbundling-rails and cssbundling-rails were added.
```
# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"

# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"
```

in package.json I see Tailwind added

```
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.0",
    "autoprefixer": "^10.4.0",
    "esbuild": "^0.14.8",
    "jquery": "^3.6.0",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.7"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css"
  }
}
```
When I add any Tailwind UI component that requires JavaScript it does not work.  For example, adding the HTML for the "simple dropdown" here https://tailwindui.com/components/application-ui/elements/dropdowns 

Adding other Tailwind elements to a page works correctly, however, anything that requires JavaScript is not rendering correctly. 

**Expected behavior**
The dropdown should open or close normally

**Actual behavior**
The dropdown is expanded on the page and does not close/open when the button is toggled. 

**System configuration**
Rails version: Rails (7.0.0)
node: 16.5.0
npm: 8.3.0
yarn 1.22.10
TailwindCSS 3.0.7

**Ruby version:**
3.0.1

**Comment by eelcoj** [comment]
The cssbundling gem with Tailwind doesn't do much of itself. 
Did you follow the steps on the [Getting set up guide](https://tailwindui.com/documentation#integrating-with-javascript-frameworks)? Based on your package.json, you are likely also interesting in the [using your own JS guide](https://tailwindui.com/documentation#using-html-and-your-own-js).
