### ISSUE TITLE
LoadError: cannot load such file -- less-rails

### ISSUE THREAD

**Issue by pk-arora** [rails/cssbundling-rails#62]
Hi there

When I try to install bootstrap using rails, I get the following error

```
D:\@UoA\sales_rep\stock>rails css:install:bootstrap
rails aborted!
LoadError: cannot load such file -- less-rails
D:/@UoA/sales_rep/stock/config/application.rb:7:in `<main>'
D:/@UoA/sales_rep/stock/Rakefile:4:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

I had already put `gem 'cssbundling-rails'`  and did `bundle install` prior to this.
I am using the following versions
ruby 2.7.2
rails 6.1.4
node v16.13.1
yarn 1.22.5
npx 8.1.2

**Comment by dhh** [comment]
Sounds like an issue with the `less-rails` gem. Please explore it over there.
