### ISSUE TITLE
Clobber task uses hardcoded path

### ISSUE THREAD

**Issue by ErikSchierboom** [rails/cssbundling-rails#64]
In [clobber.rake](https://github.com/rails/cssbundling-rails/blob/main/lib/tasks/cssbundling/clobber.rake), [line 4 has a hardcoded path](https://github.com/rails/cssbundling-rails/blob/main/lib/tasks/cssbundling/clobber.rake#L4)

```ruby
rm_rf Dir["app/assets/builds/[^.]*.css"], verbose: false
```

I think this should actually iterate over the configured assets directory/directories.

**Comment by iHiD** [comment]
Specifically, we think this should probably be any css files inside `Rails.application.config.assets.paths`. The same issue will also apply to `jsbuilding-rails` but we considered it better to have one source of truth for this discussion rather than opening two issues

**Comment by dhh** [comment]
Please do investigate a PR.
