### ISSUE TITLE
JavaScript not working for Bootstrap 5 on Rails 7

### ISSUE THREAD

**Issue by umk1** [rails/cssbundling-rails#66]
Hello,
I have started learning Ruby on Rails recently. I tried to install Bootstrap 5 with Rails 7 using this gem.
The bootstrap framework is installed, but JavaScript is not working and no dropdown menu is displayed. I tried with Navbar sample code from bootstrap website (https://getbootstrap.com/docs/5.1/components/navbar/ ), but drop-down in the Navbar does not work. Tried on Firefox browser and Google Chrome.

I did installation exactly as per instructions.

1. Added cssbundling-rails to Gemfile with gem 'cssbundling-rails'
2. Run $bundle install
3. Run $rails css:install:bootstrap

Google Chrome terminal gives this error.
Uncaught TypeError: Failed to resolve module specifier "bootstrap". Relative references must start with either "/", "./", or "../".

![Screenshot from 2022-01-15 20-42-56](https://user-images.githubusercontent.com/18586111/149645336-1d92491a-993e-410d-8476-901d581b1702.png)

Thanks.

**Comment by umk1** [comment]
File app/javascript/application.js is as follows.

```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import * as bootstrap from "bootstrap"
```
Tried to change 2nd line as import "./controllers" and import "../controllers" but that did not work.

**Comment by dhh** [comment]
Sounds like you'll probably need `jsbundling-rails` the way you're going with JavaScript. Have a look here: https://github.com/rails/jsbundling-rails/

**Comment by Ashvith** [comment]
Even after installing jsbundling-rails, components like navbar aren't working.
