### ISSUE TITLE
How to make tailwindcss and scss work together?

### ISSUE THREAD

**Issue by alec-c4** [rails/cssbundling-rails#67]
Hey!
I'm trying to make tailwindcss and scss work together, but I have some issues. I've tried 2 options

1 - `rails new app_name -c tailwind` - works fine, but I cannot use nested selectors, such as 

```scss
p {
  h1.name {
     @apply text-9xl;
  }
}
```

2 - `rails new app_name -c postcss` - works almost fine, I can use nested selectors with my postcss config

```js
module.exports = {
  plugins: [
    require('tailwindcss'),
    require('tailwindcss/nesting'),
    require('autoprefixer')
  ]
}

```

but I cannot use @import statement wit taiwindcss code (basic CSS code works fine).

application.scss

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@import "external";
```

external.scss
```css
h1 {
  @apply text-9xl;
}

body {
  background: red;
}
```

In this example body is read, but text-9xl isn't applied to h1. How to fix it?

**Comment by MrHubble** [comment]
[The readme suggests](https://github.com/rails/cssbundling-rails#how-do-i-import-relative-css-files-with-tailwind) to use `postcss-import` for `@import` statements with Tailwind. 

Don't forget to put your `@import` statements at the top of your file. For example:

```css
/* application.tailwind.css */

@import 'external';
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by MrHubble** [comment]
@alec-c4 can this issue now be closed?
