### ISSUE TITLE
Import errors when using CSSBundling + 3rd Party Gem assets

### ISSUE THREAD

**Issue by rapito** [rails/cssbundling-rails#73]
Given a rails application that uses a gem like `rails-assets-jstree`.
After trying to execute `rails css:install:sass`, I get a "Can't find stylesheet to import." error per each css asset that is inside a gem. I can perfectly follow the `@import` statement to the gem's asset.

Is there a necessary extra step to set cssbundling to be able to lookup inside included gems?

- Command Executed: `rails css:install:sass`
- Output: 
```sh
Error: Can't find stylesheet to import.
   ╷
29 │ @import 'jstree';
   │         ^^^^^^^^
   ╵
  app/assets/stylesheets/application.sass.scss 29:9  root stylesheet
error Command failed with exit code 65.

```
- `application.sass.scss`: 
```scss
// something something
@import 'jstree';
// something more
```
- `Gemfile`
```rb
source 'https://rails-assets.org' do
  gem 'rails-assets-jstree'
end
```
- jstree gem structure
![image](https://user-images.githubusercontent.com/1380104/150143398-a5efacee-0d77-4684-9edd-963b39ce7b13.png)

**Comment by dhh** [comment]
You have to manually change your Sass configuration to include the gem assets in the load path. Not something that happens automatically.
