### ISSUE TITLE
Do I need cssbundling-rails or tailwindcss-rails

### ISSUE THREAD

**Issue by andrespch** [rails/cssbundling-rails#75]
Sorry if this is not the right channel for questions.

I'm trying to integrate tailwind css into my rails app (6.1.4). I'm confuse about what's the best way to go taking into account that I'd like to upgrade to 7 as soon as possible. Do I need to move to `css-bundling` or is `tailwindcss-rails` preferable? 

thanks in advance!

**Comment by dhh** [comment]
@andrespch If you don't have any other reason to include node in your application, I would definitely suggest just using tailwindcss-rails, since there's no node dependency. If you need node for other JavaScript setups or otherwise, stick with cssbundling.

**Comment by dhh** [comment]
Recorded the difference here: https://github.com/rails/cssbundling-rails/blob/main/README.md#how-does-this-compare-to-tailwindcss-rails-and-dartsass-rails
