### ISSUE TITLE
[Question] Mixing SASS and PostCSS?

### ISSUE THREAD

**Issue by tnt175** [rails/cssbundling-rails#86]
Hi,

How would we mix both SASS and PostCSS with cssbundling-rails? With wepacker it was pretty much automatic.

I tried splitting the npm command it 2 commands like this

```
"build:css": "npm run build:css:sass && npm run build:css:postcss",
"build:css:sass": "sass ...",
"build:css:postcss": "postcss ..."
```

but this break the watch feature.

Thank you!

**Comment by dhh** [comment]
Would leave it as separate commands, then use `bin/dev` to combine both processes for development 👍
