### ISSUE TITLE
rbenv breaks an assumption in `bin/dev`.

### ISSUE THREAD

**Issue by MrJoy** [rails/cssbundling-rails#87]
Because rbenv uses shims, this line in the generated `bin/dev` script will always return true in an environment in which `foreman` has been installed in any gemset at any point, even if it's not in the current gemset:

```bash
if ! command -v foreman &> /dev/null
```

I've found this to be a viable alternative that I believe should work everywhere:

```bash
if [ $(gem list --local --no-details --quiet --exact foreman | grep foreman | wc -l) -eq 0 ]
```

(The use of `grep` is because when foreman _isn't_ installed, `gem list` will produce an empty line of output.)

**Comment by dhh** [comment]
Are there any considerations here re: Windows / WSL we need to account for if we use grep + wc?

**Comment by MrJoy** [comment]
That's an excellent question.  I've got an engineer who's using WSL that I can ask.  I will update the ticket when I have an answer.

Another option might be something like:

```bash
if ! type rbenv &> /dev/null
then
  if ! command -v foreman &> /dev/null
  then
    # ...
  fi
else
  if ! foreman version >/dev/null
  then
    # ...
  fi
fi
```

It's a little more cumbersome to be sure, but it seems like it would be viable, and compartmentalize any potential quirks / changes of semantics to just us rbenv users.

**Comment by MrJoy** [comment]
I'm informed by my colleague that when run from a Linux terminal in WSL, `grep` works fine.

**Comment by MrJoy** [comment]
@dhh What can I do to move this forward?

**Comment by t27duck** [comment]
Could `if ! foreman version &> /dev/null` be used across the board regardless if the developer is using rbenv or not?

**Comment by MrJoy** [comment]
@t27duck That solution is compatible with `rbenv`, and certainly seems lower risk.  Honestly, I feel silly that it didn't occur to me.  Might be worth tossing in a `> /dev/null 2>&1` to avoid cluttering output, since you'll get _some_ output to STDOUT/STDERR regardless of which environment you're on.

**Comment by dhh** [comment]
Sounds like @t27duck's solution would do. Feel free to PR that.

**Comment by MrJoy** [comment]
Done.
