### ISSUE TITLE
Fail fast and loud when build directory doesn't exist

### ISSUE THREAD

**Issue by Petercopter** [rails/cssbundling-rails#88]
I spent 5 hours last night debugging a production deploy that kept throwing the dreaded
```
application.css not in asset pipeline
```
This morning I realized that I had deleted `app/assets/builds` from the repo while thrashing around. That's not a problem in development, because it gets recreated (it does require a server restart). However, in production, there's no indication that anything went awry. `rake assets:precompile` runs, everything seems fine. You don't notice anything is wrong until you hit the application in the browser. Then you end up Googling for hours and realizing you've done something so incredibly wrong that most people don't do that 😄 

I was wondering if it would be possible/preferable to throw a big fat error in production when that directory doesn't exist? Or possibly just create the directory if it doesn't exist.

**Comment by erniux** [comment]
Hello, I resolved this issue in this way:
moved the javascript folder to the assets folder, and add this line to the manifest.js:  `//= link application.js`. It worked.

![image](https://user-images.githubusercontent.com/34988091/165193792-dfddc487-afe3-4f66-afd8-bed1b19341d4.png)

**Comment by dhh** [comment]
Building just delegates to the build command used by the individual libraries. So if they're failing silently, that's a difficult one to change. But we can add a note to the README.

**Comment by dhh** [comment]
https://github.com/rails/cssbundling-rails/commit/f4977d5514f097c3bc9884685e42e926a032e3a5
