### ISSUE TITLE
Issue with windows

### ISSUE THREAD

**Issue by erniux** [rails/cssbundling-rails#90]
This is how my package.json looks:

```
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@popperjs/core": "^2.11.5",
    "bootstrap": "^5.1.3",
    "bootstrap-icons": "^1.8.1",
    "esbuild": "^0.14.38",
    "sass": "^1.50.1"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules"
  }

}
```
When I paste the simple navbar into my application.html.erb and click on the dropdown menu, I got this message in the console:

`**Uncaught SyntaxError: Cannot use import statement outside a module**`

Please help, I have read in some stackoverflow that this should be fixed adding 
 "type": 

> "module",

to the package.json: ([here](https://github.com/evanw/esbuild/issues/1765))

But cant make the dropdown works :-(

Please help!!!

PS:

This is where the error is sent:

![image](https://user-images.githubusercontent.com/34988091/165195260-3f85a923-4889-453d-9dc0-ca93c427cb6b.png)

**Comment by dhh** [comment]
Not sure what the issue is, but it's with one of your custom dependencies. Not cssbundling.
