### ISSUE TITLE
Precompile url() with prefix

### ISSUE THREAD

**Issue by brianlow** [rails/cssbundling-rails#94]
I'd like 
```scss
src: url("./fonts/icons.woff2");
```
to precompile to:
```scss
src: url("/myapp1/assets/fonts/icons.woff2");
          ^^^^^^^
```

We use a shared asset host so the full path includes the application name: `assets.example.com/myapp1`. 

With webpacker we used the `publicPath` option to add the prefix. Is there an equivalent? 

ASSET_HOST seems to assume a fully qualified url. We'd prefer to avoid host names (e.g. `assets-staging.example.com`) in our compiled assets so we can use the same docker image across environments.

**Comment by dhh** [comment]
This would be something for Sprockets or Propshaft to consider.
