### ISSUE TITLE
My styles are not applied on the development server

### ISSUE THREAD

**Issue by deyemiobaa** [rails/cssbundling-rails#97]
Hello, I added cssbundling-rails to an existing rails project with the instructions provided. When I add styles via classes to my .html.erb files, they get added to the application.css after `yarn build:css` but when I start the rails server those changes don't reflect on the web.

html.erb file
![image](https://user-images.githubusercontent.com/55185309/180504321-3a9119eb-b218-4a33-9ae9-eaa5707df68d.png)

assets/builds/application.css file
![image](https://user-images.githubusercontent.com/55185309/180504492-53c85725-6d63-434f-a1ec-c1f4f7f42e4c.png)

dev server
![image](https://user-images.githubusercontent.com/55185309/180504896-c6d260e5-a828-407b-b2ea-f3d39f72e308.png)

**Comment by jwilsjustin** [comment]
Is the stylesheet loaded in the <head> of your HTML page? You may need to add `<%= stylesheet_link_tag "application" %>` to your `app/views/layouts/application.html.erb` file.

**Comment by abevoelker** [comment]
Also if you're using Propshaft, be sure you didn't run `rails assets:precompile` or you'll be serving stale assets. You can reset things by running

```
$ rails assets:clobber
```

**Comment by cesar82** [comment]
Hi, I am having same issue, it looks you need to run "yarn build:css" to get your css changes
or use in other terminal "yarn build:css --watch"
